author: "Prolific Interactive"
dependencies:
  dio: "2.0.1"
  flutter:
    sdk: flutter
  package_info: ^0.4.0+3
description: "A debug menu for Flutter"
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.1.0 <3.0.0"
flutter:
  assets:
    - lib/assets/check_circle/check_circle.png
    - lib/assets/check_circle_outline/check_circle_outline.png
homepage: github.com/prolificinteractive
name: debug_menu
version: "0.0.1"
